/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Clases;

/**
 *
 * @author Camila Garcia
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.ganadorLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloSW = new javax.swing.JLabel();
        tituloST = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        contadorVictoriasSW = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        contadorVictoriasST1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        contadorVictoriasST = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        contadorVictoriasST3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        lblColaUS6 = new javax.swing.JLabel();
        lblColaUS7 = new javax.swing.JLabel();
        lblColaUS8 = new javax.swing.JLabel();
        lblColaUS9 = new javax.swing.JLabel();
        lblColaUS10 = new javax.swing.JLabel();
        lblColaUS11 = new javax.swing.JLabel();
        lblColaUS12 = new javax.swing.JLabel();
        lblColaUS13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        estadoLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        resultadoLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ganadorLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        personajeSWlabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        personajeSWlabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        personajeSTlabel = new javax.swing.JLabel();
        selecionadoSTlabel = new javax.swing.JLabel();
        seleccionadoSWlabel = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();
        valorSlider = new javax.swing.JLabel();
        titleAV5 = new javax.swing.JLabel();
        titleAV3 = new javax.swing.JLabel();
        titleAV4 = new javax.swing.JLabel();
        titleAV = new javax.swing.JLabel();
        titleAV7 = new javax.swing.JLabel();
        titleAV6 = new javax.swing.JLabel();
        titleAV8 = new javax.swing.JLabel();
        titleAV1 = new javax.swing.JLabel();
        valorPuntosdeVidaST = new javax.swing.JLabel();
        valorAgilidadST = new javax.swing.JLabel();
        valorFuerzaST = new javax.swing.JLabel();
        valorHabilidadesST = new javax.swing.JLabel();
        valorsFuerzaSW = new javax.swing.JLabel();
        valorHabilidadesSW = new javax.swing.JLabel();
        valorPuntosdeVidaSW = new javax.swing.JLabel();
        valorAgilidadSW = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloSW.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        tituloSW.setText("Star Wars");
        jPanel1.add(tituloSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 0, 240, 60));

        tituloST.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        tituloST.setText("Star Trek");
        jPanel1.add(tituloST, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 240, 60));

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contadorVictoriasSW.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contadorVictoriasSW.setForeground(new java.awt.Color(0, 0, 0));
        contadorVictoriasSW.setText("0");
        jPanel2.add(contadorVictoriasSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 70, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Victorias:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contadorVictoriasST1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contadorVictoriasST1.setText("0");
        jPanel3.add(contadorVictoriasST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Victorias:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 190, 30));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contadorVictoriasST.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contadorVictoriasST.setText("0");
        jPanel4.add(contadorVictoriasST, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Victorias:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 0, 153)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contadorVictoriasST3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contadorVictoriasST3.setText("0");
        jPanel5.add(contadorVictoriasST3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 70, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Victorias:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 70, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 180, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 190, 30));

        jTextArea1.setBackground(new java.awt.Color(0, 0, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 190, 90));

        jTextArea2.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, 190, 90));

        jTextArea3.setBackground(new java.awt.Color(255, 204, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setRows(5);
        jTextArea3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, 190, 90));

        jTextArea4.setBackground(new java.awt.Color(0, 0, 102));
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 190, 90));

        jTextArea5.setBackground(new java.awt.Color(0, 0, 153));
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jScrollPane5.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 190, 90));

        jTextArea6.setBackground(new java.awt.Color(255, 255, 153));
        jTextArea6.setColumns(20);
        jTextArea6.setForeground(new java.awt.Color(255, 204, 153));
        jTextArea6.setRows(5);
        jTextArea6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane6.setViewportView(jTextArea6);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, 190, 90));

        jTextArea7.setBackground(new java.awt.Color(255, 204, 51));
        jTextArea7.setColumns(20);
        jTextArea7.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea7.setRows(5);
        jTextArea7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane7.setViewportView(jTextArea7);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, 190, 90));

        jTextArea8.setBackground(new java.awt.Color(51, 51, 255));
        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jTextArea8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        jScrollPane8.setViewportView(jTextArea8);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 190, 90));

        lblColaUS6.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS6.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS6.setText("Cola 1");
        lblColaUS6.setOpaque(true);
        jPanel1.add(lblColaUS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 50, -1));

        lblColaUS7.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS7.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS7.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS7.setText("Cola 2");
        lblColaUS7.setOpaque(true);
        jPanel1.add(lblColaUS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, 50, -1));

        lblColaUS8.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS8.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS8.setText("Cola 3");
        lblColaUS8.setOpaque(true);
        jPanel1.add(lblColaUS8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 50, -1));

        lblColaUS9.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS9.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS9.setText("Cola 1");
        lblColaUS9.setOpaque(true);
        jPanel1.add(lblColaUS9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 50, -1));

        lblColaUS10.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS10.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS10.setText("Cola 2");
        lblColaUS10.setOpaque(true);
        jPanel1.add(lblColaUS10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 50, -1));

        lblColaUS11.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS11.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS11.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS11.setText("Cola 3");
        lblColaUS11.setOpaque(true);
        jPanel1.add(lblColaUS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 50, -1));

        lblColaUS12.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS12.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS12.setText("Refuerzo");
        lblColaUS12.setOpaque(true);
        jPanel1.add(lblColaUS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 50, -1));

        lblColaUS13.setBackground(new java.awt.Color(0, 0, 0));
        lblColaUS13.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblColaUS13.setForeground(new java.awt.Color(255, 255, 255));
        lblColaUS13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColaUS13.setText("Refuerzo");
        lblColaUS13.setOpaque(true);
        jPanel1.add(lblColaUS13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 440, 50, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estadoLabel.setBackground(new java.awt.Color(255, 255, 255));
        estadoLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        estadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(estadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 230, 40));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resultadoLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resultadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(resultadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 230, 40));

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ganadorLabel.setBackground(new java.awt.Color(0, 0, 0));
        ganadorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ganadorLabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel8.add(ganadorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 40));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 520, 230, 40));

        jPanel9.setBackground(new java.awt.Color(255, 204, 0));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("jLabel7");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, -1, -1));

        personajeSWlabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        personajeSWlabel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel9.add(personajeSWlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));

        jPanel11.setBackground(new java.awt.Color(255, 204, 0));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("jLabel7");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, -1, -1));

        personajeSWlabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        personajeSWlabel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel11.add(personajeSWlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 40));

        jPanel9.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 290, 40));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 290, 40));

        jPanel10.setBackground(new java.awt.Color(0, 0, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("jLabel3");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 50, 50));

        personajeSTlabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel10.add(personajeSTlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 310, 40));

        selecionadoSTlabel.setBackground(new java.awt.Color(0, 0, 102));
        selecionadoSTlabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        selecionadoSTlabel.setForeground(new java.awt.Color(255, 255, 255));
        selecionadoSTlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecionadoSTlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        selecionadoSTlabel.setOpaque(true);
        jPanel1.add(selecionadoSTlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 310, 50));

        seleccionadoSWlabel.setBackground(new java.awt.Color(255, 204, 51));
        seleccionadoSWlabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        seleccionadoSWlabel.setForeground(new java.awt.Color(0, 0, 0));
        seleccionadoSWlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seleccionadoSWlabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        seleccionadoSWlabel.setOpaque(true);
        jPanel1.add(seleccionadoSWlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 530, 290, 50));

        slider.setBackground(new java.awt.Color(255, 255, 255));
        slider.setForeground(new java.awt.Color(0, 0, 0));
        slider.setMaximum(15);
        slider.setMinimum(5);
        slider.setMinorTickSpacing(1);
        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setSnapToTicks(true);
        slider.setToolTipText("");
        slider.setValue(10);
        slider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        slider.setMinimumSize(new java.awt.Dimension(18, 16));
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        jPanel1.add(slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 230, 30));

        valorSlider.setBackground(new java.awt.Color(255, 255, 255));
        valorSlider.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        valorSlider.setForeground(new java.awt.Color(0, 0, 0));
        valorSlider.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorSlider.setText("10");
        valorSlider.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        valorSlider.setOpaque(true);
        jPanel1.add(valorSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 230, 20));

        titleAV5.setBackground(new java.awt.Color(0, 0, 0));
        titleAV5.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV5.setForeground(new java.awt.Color(255, 255, 255));
        titleAV5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV5.setText("HABILIDADES");
        titleAV5.setOpaque(true);
        jPanel1.add(titleAV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 600, 110, 20));

        titleAV3.setBackground(new java.awt.Color(0, 0, 0));
        titleAV3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV3.setForeground(new java.awt.Color(255, 255, 255));
        titleAV3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV3.setText("PUNTOS DE VIDA");
        titleAV3.setOpaque(true);
        jPanel1.add(titleAV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 620, 130, 20));

        titleAV4.setBackground(new java.awt.Color(0, 0, 0));
        titleAV4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV4.setForeground(new java.awt.Color(255, 255, 255));
        titleAV4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV4.setText("AGILIDAD");
        titleAV4.setOpaque(true);
        jPanel1.add(titleAV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 640, 80, 20));

        titleAV.setBackground(new java.awt.Color(0, 0, 0));
        titleAV.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV.setForeground(new java.awt.Color(255, 255, 255));
        titleAV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV.setText("FUERZA");
        titleAV.setOpaque(true);
        jPanel1.add(titleAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 660, 60, 20));

        titleAV7.setBackground(new java.awt.Color(0, 0, 0));
        titleAV7.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV7.setForeground(new java.awt.Color(255, 255, 255));
        titleAV7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV7.setText("HABILIDADES");
        titleAV7.setOpaque(true);
        jPanel1.add(titleAV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 110, 20));

        titleAV6.setBackground(new java.awt.Color(0, 0, 0));
        titleAV6.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV6.setForeground(new java.awt.Color(255, 255, 255));
        titleAV6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV6.setText("PUNTOS DE VIDA");
        titleAV6.setOpaque(true);
        jPanel1.add(titleAV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 130, 20));

        titleAV8.setBackground(new java.awt.Color(0, 0, 0));
        titleAV8.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV8.setForeground(new java.awt.Color(255, 255, 255));
        titleAV8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV8.setText("AGILIDAD");
        titleAV8.setOpaque(true);
        jPanel1.add(titleAV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 80, 20));

        titleAV1.setBackground(new java.awt.Color(0, 0, 0));
        titleAV1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        titleAV1.setForeground(new java.awt.Color(255, 255, 255));
        titleAV1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleAV1.setText("FUERZA");
        titleAV1.setOpaque(true);
        jPanel1.add(titleAV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 660, 60, 20));

        valorPuntosdeVidaST.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorPuntosdeVidaST.setForeground(new java.awt.Color(255, 255, 255));
        valorPuntosdeVidaST.setText("0");
        jPanel1.add(valorPuntosdeVidaST, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 80, -1));

        valorAgilidadST.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorAgilidadST.setForeground(new java.awt.Color(255, 255, 255));
        valorAgilidadST.setText("0");
        jPanel1.add(valorAgilidadST, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, 80, -1));

        valorFuerzaST.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorFuerzaST.setForeground(new java.awt.Color(255, 255, 255));
        valorFuerzaST.setText("0");
        jPanel1.add(valorFuerzaST, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 660, 80, -1));

        valorHabilidadesST.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorHabilidadesST.setForeground(new java.awt.Color(255, 255, 255));
        valorHabilidadesST.setText("0");
        jPanel1.add(valorHabilidadesST, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 80, -1));

        valorsFuerzaSW.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorsFuerzaSW.setForeground(new java.awt.Color(255, 255, 255));
        valorsFuerzaSW.setText("0");
        jPanel1.add(valorsFuerzaSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 660, 50, -1));

        valorHabilidadesSW.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorHabilidadesSW.setForeground(new java.awt.Color(255, 255, 255));
        valorHabilidadesSW.setText("0");
        jPanel1.add(valorHabilidadesSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 50, -1));

        valorPuntosdeVidaSW.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorPuntosdeVidaSW.setForeground(new java.awt.Color(255, 255, 255));
        valorPuntosdeVidaSW.setText("0");
        jPanel1.add(valorPuntosdeVidaSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 620, 50, -1));

        valorAgilidadSW.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorAgilidadSW.setForeground(new java.awt.Color(255, 255, 255));
        valorAgilidadSW.setText("0");
        jPanel1.add(valorAgilidadSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, 50, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StarTrekVs.StarWars-original (2).jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, -1, 870));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
    valorSlider.setText(Integer.toString(slider.getValue()));
    Main.duracion= Integer.parseInt(this.getDuracion())*1000;
    }//GEN-LAST:event_sliderStateChanged

    public String getDuracion(){
        return valorSlider.getText();
    }
    
   
    
            
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contadorVictoriasST;
    private javax.swing.JLabel contadorVictoriasST1;
    private javax.swing.JLabel contadorVictoriasST3;
    private javax.swing.JLabel contadorVictoriasSW;
    private javax.swing.JLabel estadoLabel;
    private javax.swing.JLabel ganadorLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JLabel lblColaUS10;
    private javax.swing.JLabel lblColaUS11;
    private javax.swing.JLabel lblColaUS12;
    private javax.swing.JLabel lblColaUS13;
    private javax.swing.JLabel lblColaUS6;
    private javax.swing.JLabel lblColaUS7;
    private javax.swing.JLabel lblColaUS8;
    private javax.swing.JLabel lblColaUS9;
    private javax.swing.JLabel personajeSTlabel;
    private javax.swing.JLabel personajeSWlabel;
    private javax.swing.JLabel personajeSWlabel1;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JLabel seleccionadoSWlabel;
    private javax.swing.JLabel selecionadoSTlabel;
    private javax.swing.JSlider slider;
    private javax.swing.JLabel titleAV;
    private javax.swing.JLabel titleAV1;
    private javax.swing.JLabel titleAV3;
    private javax.swing.JLabel titleAV4;
    private javax.swing.JLabel titleAV5;
    private javax.swing.JLabel titleAV6;
    private javax.swing.JLabel titleAV7;
    private javax.swing.JLabel titleAV8;
    private javax.swing.JLabel tituloST;
    private javax.swing.JLabel tituloSW;
    private javax.swing.JLabel valorAgilidadST;
    private javax.swing.JLabel valorAgilidadSW;
    private javax.swing.JLabel valorFuerzaST;
    private javax.swing.JLabel valorHabilidadesST;
    private javax.swing.JLabel valorHabilidadesSW;
    private javax.swing.JLabel valorPuntosdeVidaST;
    private javax.swing.JLabel valorPuntosdeVidaSW;
    private javax.swing.JLabel valorSlider;
    private javax.swing.JLabel valorsFuerzaSW;
    // End of variables declaration//GEN-END:variables
}
